name: golangci-lint

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Repository info
        run: |
          echo "Checking out the code from the repository..."
          echo "Repository: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: Go environment info
        run: |
          echo "Setting up Go environment..."
          echo "Using Go version: $(go version)"

      - name: Install dependencies
        run: |
          echo "Starting dependency installation..."
          go mod download
          echo "Dependencies installed successfully."
          echo "Listing all Go modules:"
          go list -m all

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56
          args: --timeout 10m
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Debug golangci-lint logs
        if: failure()
        run: |
          echo "Linting failed. Printing debug information..."
          echo "Listing all Go modules:"
          go list -m all
          echo "Checking Go environment:"
          go env
          echo "Checking Go version:"
          go version
          echo "Linting failure analysis complete."
